name: Runsys
description: "Runsys - property management solution"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  http: ^1.6.0
  device_info_plus: ^12.0.0
  image_picker: ^1.0.4
  image_cropper: ^12.2.1
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/runsys-adaptive-fg.png"
  adaptive_icon_background: "#421A86"
  adaptive_icon_foreground: "assets/icons/runsys-adaptive-fg.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/user-image.png
    - assets/icons/